### ISSUE TITLE
Задание 9. Добавить команду /transfer

### ISSUE THREAD

**Issue by saneci** [gpb-it-factory/gladskoy-telegram-bot#15]
**Задача команды:** перевод средств со счёта текущего пользователя на другой счёт по имени пользователя, параметры:

- `toTelegramUser` - пользователь, на счёт которого совершается перевод
-  `amount` - сумма перевода

**TODO:**

- [x] Обновить контракт Middle Service 
- [x] Написать тесты
- [x] Реализовать бизнес-логику
- [x] Обновить версию приложения
- [ ] После апрува PR Проставить тег
