### ISSUE TITLE
Добавить команду /help

### ISSUE THREAD

**Issue by saneci** [gpb-it-factory/gladskoy-telegram-bot#32]
Результат выполнения команды должен содержать список всех доступных команд с кратким описанием

**TODO:**

- [x] Реализовать бизнес-логику
- [x] Написать тесты
- [x] Обновить версию приложения
- [ ] После апрува PR Проставить тег
