### ISSUE TITLE
Уменьшить в команде /register количество запросов к Middle Service

### ISSUE THREAD

**Issue by saneci** [gpb-it-factory/gladskoy-telegram-bot#33]
### Проблема

Сейчас при каждой обработке команды `/register` происходит попытка создания нового пользователя в Middle Service. Если клиент уже зарегистрирован, возвращается 422. Необходимо изменить это поведение с целью сокращения количества вызовов и ошибок.

### Решение

Внести изменения в алгоритм:

1. Получаем запрос от бота с командой `/register`
2. Запрашиваем в Middle Service данные пользователя
    1. Если пользователь существует, добавляем данные в кэш и возвращаем сообщение: "`Вы уже зарегистрированы ранее!`"
    2. Иначе создаём нового пользователя
3. Возвращаем ответ пользователю: "`Вы успешно зарегистрированы!`"

⚠ Сделать после выполнения задачи https://github.com/gpb-it-factory/gladskoy-middle-service/issues/10

**TODO:**

- [x] Написать тесты
- [x] Исправить бизнес-логику
- [x] Обновить версию приложения
- [x] После апрува PR Проставить тег
